export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_TO_CART';

export const UPDATE_CART_TOTAL = 'UPDATE_CART_TOTAL';

export const TOGGLE_SIDEBAR_HIDDEN = 'TOGGLE_SIDEBAR_HIDDEN';