export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';

export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_TO_CART';

export const UPDATE_CART_TOTAL = 'UPDATE_CART_TOTAL';

export const CLEAR_CART = 'CLEAR_CART';

export const CREATE_LINE_ITEMS_FROM_CART = 'CREATE_LINE_ITEMS_FROM_CART';

export const TOGGLE_SIDEBAR_HIDDEN = 'TOGGLE_SIDEBAR_HIDDEN';